<?php

/**
 * SCF Enterprise ERP Module Registry.
 * Each module defines schema, routing, and sidebar placement.
 */
return [

    // Batch 1 — Platform & Multi-Branch
    'branches' => [
        'model' => 'Branch',
        'table' => 'branches',
        'route' => 'branches',
        'prefix' => 'administration',
        'sidebar' => ['group' => 'Administration', 'icon' => 'building-office', 'label' => 'Branches'],
        'permission' => 'branches',
        'fields' => [
            'name' => 'string|required',
            'code' => 'string|unique|required',
            'address' => 'text|nullable',
            'phone' => 'string|nullable',
            'email' => 'string|nullable',
            'is_active' => 'boolean|default:true',
        ],
    ],
    'notification-templates' => [
        'model' => 'NotificationTemplate',
        'table' => 'notification_templates',
        'route' => 'notification-templates',
        'prefix' => 'administration',
        'sidebar' => ['group' => 'Administration', 'icon' => 'bell', 'label' => 'Notification templates'],
        'permission' => 'notification-templates',
        'fields' => [
            'name' => 'string|required',
            'code' => 'string|unique|required',
            'channel' => 'string|default:email',
            'subject' => 'string|required',
            'body' => 'text|required',
            'is_active' => 'boolean|default:true',
        ],
    ],
    'notifications' => [
        'model' => 'DatabaseNotification',
        'table' => 'notifications',
        'route' => 'notifications',
        'prefix' => 'administration',
        'sidebar' => ['group' => 'Administration', 'icon' => 'bell-alert', 'label' => 'Notification Center'],
        'permission' => 'notifications',
        'fields' => [],
    ],
    'variants' => [
        'model' => 'Variant',
        'table' => 'variants',
        'route' => 'variants',
        'prefix' => 'inventory',
        'sidebar' => ['group' => 'Inventory', 'icon' => 'squares-2x2', 'label' => 'Variants'],
        'permission' => 'variants',
        'fields' => [
            'product_id' => 'foreignId:products|required',
            'name' => 'string|required',
            'sku' => 'string|unique|required',
            'barcode' => 'string|nullable',
            'sale_price' => 'decimal:12,2|default:0',
            'purchase_price' => 'decimal:12,2|default:0',
            'stock_quantity' => 'integer|default:0',
            'is_active' => 'boolean|default:true',
        ],
    ],
    'price-lists' => [
        'model' => 'PriceList',
        'table' => 'price_lists',
        'route' => 'price-lists',
        'prefix' => 'inventory',
        'sidebar' => ['group' => 'Inventory', 'icon' => 'tag', 'label' => 'Price lists'],
        'permission' => 'price-lists',
        'fields' => [
            'name' => 'string|required',
            'code' => 'string|unique|required',
            'currency' => 'string|default:USD',
            'valid_from' => 'date|nullable',
            'valid_until' => 'date|nullable',
            'is_active' => 'boolean|default:true',
        ],
    ],

    // Batch 2 — Manufacturing & Logistics
    'production-orders' => [
        'model' => 'ProductionOrder',
        'table' => 'production_orders',
        'route' => 'production-orders',
        'prefix' => 'manufacturing',
        'sidebar' => ['group' => 'Manufacturing', 'icon' => 'cog-6-tooth', 'label' => 'Production orders'],
        'permission' => 'production-orders',
        'status_enum' => 'ProductionOrderStatus',
        'fields' => [
            'reference_number' => 'string|unique|required',
            'product_id' => 'foreignId:products|required',
            'warehouse_id' => 'foreignId:warehouses|nullable',
            'branch_id' => 'foreignId:branches|nullable',
            'quantity' => 'integer|required',
            'start_date' => 'date|required',
            'end_date' => 'date|nullable',
            'status' => 'string|default:draft',
            'notes' => 'text|nullable',
        ],
    ],
    'bill-of-materials' => [
        'model' => 'BillOfMaterial',
        'table' => 'bill_of_materials',
        'route' => 'bill-of-materials',
        'prefix' => 'manufacturing',
        'sidebar' => ['group' => 'Manufacturing', 'icon' => 'list-bullet', 'label' => 'Bill of materials'],
        'permission' => 'bill-of-materials',
        'fields' => [
            'product_id' => 'foreignId:products|required',
            'component_product_id' => 'foreignId:products|required',
            'quantity' => 'decimal:12,4|required',
            'unit' => 'string|default:pcs',
            'notes' => 'text|nullable',
        ],
    ],
    'quality-controls' => [
        'model' => 'QualityControl',
        'table' => 'quality_controls',
        'route' => 'quality-controls',
        'prefix' => 'manufacturing',
        'sidebar' => ['group' => 'Manufacturing', 'icon' => 'shield-check', 'label' => 'Quality control'],
        'permission' => 'quality-control',
        'status_enum' => 'QualityControlStatus',
        'fields' => [
            'reference_number' => 'string|unique|required',
            'production_order_id' => 'foreignId:production_orders|nullable',
            'product_id' => 'foreignId:products|required',
            'inspection_date' => 'date|required',
            'status' => 'string|default:pending',
            'passed_quantity' => 'integer|default:0',
            'failed_quantity' => 'integer|default:0',
            'notes' => 'text|nullable',
        ],
    ],
    'shipping-methods' => [
        'model' => 'ShippingMethod',
        'table' => 'shipping_methods',
        'route' => 'shipping-methods',
        'prefix' => 'warehouse',
        'sidebar' => ['group' => 'Warehouse', 'icon' => 'truck', 'label' => 'Shipping methods'],
        'permission' => 'shipping-methods',
        'fields' => [
            'name' => 'string|required',
            'code' => 'string|unique|required',
            'carrier' => 'string|nullable',
            'base_cost' => 'decimal:12,2|default:0',
            'is_active' => 'boolean|default:true',
        ],
    ],
    'delivery-trips' => [
        'model' => 'DeliveryTrip',
        'table' => 'delivery_trips',
        'route' => 'delivery-trips',
        'prefix' => 'warehouse',
        'sidebar' => ['group' => 'Warehouse', 'icon' => 'map', 'label' => 'Delivery trips'],
        'permission' => 'delivery-trips',
        'status_enum' => 'DeliveryTripStatus',
        'fields' => [
            'reference_number' => 'string|unique|required',
            'shipping_method_id' => 'foreignId:shipping_methods|nullable',
            'driver_name' => 'string|nullable',
            'vehicle_plate' => 'string|nullable',
            'trip_date' => 'date|required',
            'status' => 'string|default:planned',
            'notes' => 'text|nullable',
        ],
    ],

    // Batch 3 — HR
    'attendance' => [
        'model' => 'Attendance',
        'table' => 'attendances',
        'route' => 'attendance',
        'prefix' => 'hr',
        'sidebar' => ['group' => 'HR', 'icon' => 'clock', 'label' => 'Attendance'],
        'permission' => 'attendance',
        'fields' => [
            'employee_id' => 'foreignId:employees|required',
            'branch_id' => 'foreignId:branches|nullable',
            'attendance_date' => 'date|required',
            'check_in' => 'time|nullable',
            'check_out' => 'time|nullable',
            'status' => 'string|default:present',
            'notes' => 'text|nullable',
        ],
    ],
    'leave-requests' => [
        'model' => 'LeaveRequest',
        'table' => 'leave_requests',
        'route' => 'leave-requests',
        'prefix' => 'hr',
        'sidebar' => ['group' => 'HR', 'icon' => 'calendar-days', 'label' => 'Leave requests'],
        'permission' => 'leave-requests',
        'status_enum' => 'LeaveRequestStatus',
        'fields' => [
            'employee_id' => 'foreignId:employees|required',
            'leave_type' => 'string|required',
            'start_date' => 'date|required',
            'end_date' => 'date|required',
            'status' => 'string|default:pending',
            'reason' => 'text|nullable',
        ],
    ],
    'shift-management' => [
        'model' => 'Shift',
        'table' => 'shifts',
        'route' => 'shifts',
        'prefix' => 'hr',
        'sidebar' => ['group' => 'HR', 'icon' => 'arrow-path', 'label' => 'Shift management'],
        'permission' => 'shift-management',
        'fields' => [
            'name' => 'string|required',
            'branch_id' => 'foreignId:branches|nullable',
            'start_time' => 'time|required',
            'end_time' => 'time|required',
            'is_active' => 'boolean|default:true',
        ],
    ],
    'performance-reviews' => [
        'model' => 'PerformanceReview',
        'table' => 'performance_reviews',
        'route' => 'performance-reviews',
        'prefix' => 'hr',
        'sidebar' => ['group' => 'HR', 'icon' => 'star', 'label' => 'Performance reviews'],
        'permission' => 'performance-reviews',
        'status_enum' => 'PerformanceReviewStatus',
        'fields' => [
            'employee_id' => 'foreignId:employees|required',
            'review_date' => 'date|required',
            'rating' => 'integer|default:0',
            'status' => 'string|default:draft',
            'comments' => 'text|nullable',
        ],
    ],
    'vehicle-maintenance' => [
        'model' => 'VehicleMaintenance',
        'table' => 'vehicle_maintenances',
        'route' => 'vehicle-maintenance',
        'prefix' => 'warehouse',
        'sidebar' => ['group' => 'Warehouse', 'icon' => 'wrench-screwdriver', 'label' => 'Vehicle maintenance'],
        'permission' => 'vehicle-maintenance',
        'status_enum' => 'VehicleMaintenanceStatus',
        'fields' => [
            'vehicle_plate' => 'string|required',
            'maintenance_date' => 'date|required',
            'maintenance_type' => 'string|required',
            'cost' => 'decimal:12,2|default:0',
            'status' => 'string|default:scheduled',
            'notes' => 'text|nullable',
        ],
    ],

    // Batch 4 — CRM & Marketing
    'leads' => [
        'model' => 'Lead',
        'table' => 'leads',
        'route' => 'leads',
        'prefix' => 'crm',
        'sidebar' => ['group' => 'CRM', 'icon' => 'funnel', 'label' => 'Lead management'],
        'permission' => 'leads',
        'status_enum' => 'LeadStatus',
        'fields' => [
            'name' => 'string|required',
            'email' => 'string|nullable',
            'phone' => 'string|nullable',
            'company' => 'string|nullable',
            'source' => 'string|nullable',
            'status' => 'string|default:new',
            'estimated_value' => 'decimal:12,2|default:0',
            'notes' => 'text|nullable',
        ],
    ],
    'customer-feedback' => [
        'model' => 'CustomerFeedback',
        'table' => 'customer_feedbacks',
        'route' => 'customer-feedback',
        'prefix' => 'crm',
        'sidebar' => ['group' => 'CRM', 'icon' => 'hand-thumb-up', 'label' => 'Customer feedback'],
        'permission' => 'customer-feedback',
        'fields' => [
            'contact_id' => 'foreignId:contacts|required',
            'rating' => 'integer|required',
            'subject' => 'string|required',
            'feedback' => 'text|required',
            'feedback_date' => 'date|required',
        ],
    ],
    'campaigns' => [
        'model' => 'Campaign',
        'table' => 'campaigns',
        'route' => 'campaigns',
        'prefix' => 'marketing',
        'sidebar' => ['group' => 'Marketing', 'icon' => 'megaphone', 'label' => 'Campaigns'],
        'permission' => 'campaigns',
        'status_enum' => 'CampaignStatus',
        'fields' => [
            'name' => 'string|required',
            'code' => 'string|unique|required',
            'start_date' => 'date|required',
            'end_date' => 'date|nullable',
            'budget' => 'decimal:12,2|default:0',
            'status' => 'string|default:draft',
            'description' => 'text|nullable',
        ],
    ],
    'loyalty-programs' => [
        'model' => 'LoyaltyProgram',
        'table' => 'loyalty_programs',
        'route' => 'loyalty-programs',
        'prefix' => 'marketing',
        'sidebar' => ['group' => 'Marketing', 'icon' => 'gift', 'label' => 'Loyalty programs'],
        'permission' => 'loyalty-programs',
        'fields' => [
            'name' => 'string|required',
            'code' => 'string|unique|required',
            'points_per_currency' => 'decimal:8,2|default:1',
            'is_active' => 'boolean|default:true',
            'description' => 'text|nullable',
        ],
    ],
    'coupons' => [
        'model' => 'Coupon',
        'table' => 'coupons',
        'route' => 'coupons',
        'prefix' => 'marketing',
        'sidebar' => ['group' => 'Marketing', 'icon' => 'ticket', 'label' => 'Coupons'],
        'permission' => 'coupons',
        'fields' => [
            'code' => 'string|unique|required',
            'discount_type' => 'string|default:percentage',
            'discount_value' => 'decimal:12,2|required',
            'valid_from' => 'date|nullable',
            'valid_until' => 'date|nullable',
            'usage_limit' => 'integer|nullable',
            'is_active' => 'boolean|default:true',
        ],
    ],

    // Batch 5 — Accounting Deep
    'fixed-assets' => [
        'model' => 'FixedAsset',
        'table' => 'fixed_assets',
        'route' => 'fixed-assets',
        'prefix' => 'accounting',
        'sidebar' => ['group' => 'Accounting', 'icon' => 'building-library', 'label' => 'Fixed assets'],
        'permission' => 'fixed-assets',
        'fields' => [
            'name' => 'string|required',
            'asset_code' => 'string|unique|required',
            'purchase_date' => 'date|required',
            'purchase_cost' => 'decimal:12,2|required',
            'current_value' => 'decimal:12,2|default:0',
            'branch_id' => 'foreignId:branches|nullable',
            'notes' => 'text|nullable',
        ],
    ],
    'budgeting' => [
        'model' => 'Budget',
        'table' => 'budgets',
        'route' => 'budgets',
        'prefix' => 'accounting',
        'sidebar' => ['group' => 'Accounting', 'icon' => 'chart-pie', 'label' => 'Budgeting'],
        'permission' => 'budgeting',
        'fields' => [
            'name' => 'string|required',
            'reference_number' => 'string|unique|required',
            'period_start' => 'date|required',
            'period_end' => 'date|required',
            'allocated_amount' => 'decimal:12,2|required',
            'spent_amount' => 'decimal:12,2|default:0',
            'branch_id' => 'foreignId:branches|nullable',
            'notes' => 'text|nullable',
        ],
    ],
    'bank-reconciliation' => [
        'model' => 'BankReconciliation',
        'table' => 'bank_reconciliations',
        'route' => 'bank-reconciliations',
        'prefix' => 'accounting',
        'sidebar' => ['group' => 'Accounting', 'icon' => 'building-office-2', 'label' => 'Bank reconciliation'],
        'permission' => 'bank-reconciliation',
        'status_enum' => 'BankReconciliationStatus',
        'fields' => [
            'reference_number' => 'string|unique|required',
            'bank_name' => 'string|required',
            'statement_date' => 'date|required',
            'opening_balance' => 'decimal:12,2|default:0',
            'closing_balance' => 'decimal:12,2|default:0',
            'status' => 'string|default:draft',
            'notes' => 'text|nullable',
        ],
    ],
    'gift-cards' => [
        'model' => 'GiftCard',
        'table' => 'gift_cards',
        'route' => 'gift-cards',
        'prefix' => 'marketing',
        'sidebar' => ['group' => 'Marketing', 'icon' => 'credit-card', 'label' => 'Gift cards'],
        'permission' => 'gift-cards',
        'fields' => [
            'code' => 'string|unique|required',
            'initial_balance' => 'decimal:12,2|required',
            'current_balance' => 'decimal:12,2|required',
            'contact_id' => 'foreignId:contacts|nullable',
            'expires_at' => 'date|nullable',
            'is_active' => 'boolean|default:true',
        ],
    ],
    'subscriptions' => [
        'model' => 'Subscription',
        'table' => 'subscriptions',
        'route' => 'subscriptions',
        'prefix' => 'marketing',
        'sidebar' => ['group' => 'Marketing', 'icon' => 'arrow-path-rounded-square', 'label' => 'Subscriptions'],
        'permission' => 'subscriptions',
        'status_enum' => 'SubscriptionStatus',
        'fields' => [
            'contact_id' => 'foreignId:contacts|required',
            'plan_name' => 'string|required',
            'start_date' => 'date|required',
            'end_date' => 'date|nullable',
            'amount' => 'decimal:12,2|required',
            'billing_cycle' => 'string|default:monthly',
            'status' => 'string|default:active',
        ],
    ],

    // Batch 6 — Projects & Support
    'contracts' => [
        'model' => 'Contract',
        'table' => 'contracts',
        'route' => 'contracts',
        'prefix' => 'projects',
        'sidebar' => ['group' => 'Projects', 'icon' => 'document-check', 'label' => 'Contracts'],
        'permission' => 'contracts',
        'status_enum' => 'ContractStatus',
        'fields' => [
            'reference_number' => 'string|unique|required',
            'contact_id' => 'foreignId:contacts|required',
            'title' => 'string|required',
            'start_date' => 'date|required',
            'end_date' => 'date|nullable',
            'value' => 'decimal:12,2|default:0',
            'status' => 'string|default:draft',
            'notes' => 'text|nullable',
        ],
    ],
    'project-tasks' => [
        'model' => 'ProjectTask',
        'table' => 'project_tasks',
        'route' => 'project-tasks',
        'prefix' => 'projects',
        'sidebar' => ['group' => 'Projects', 'icon' => 'clipboard-document-check', 'label' => 'Project tasks'],
        'permission' => 'project-tasks',
        'status_enum' => 'ProjectTaskStatus',
        'fields' => [
            'contract_id' => 'foreignId:contracts|nullable',
            'employee_id' => 'foreignId:employees|nullable',
            'title' => 'string|required',
            'due_date' => 'date|nullable',
            'priority' => 'string|default:medium',
            'status' => 'string|default:todo',
            'description' => 'text|nullable',
        ],
    ],
    'time-logs' => [
        'model' => 'TimeLog',
        'table' => 'time_logs',
        'route' => 'time-logs',
        'prefix' => 'projects',
        'sidebar' => ['group' => 'Projects', 'icon' => 'clock', 'label' => 'Time logs'],
        'permission' => 'time-logs',
        'fields' => [
            'project_task_id' => 'foreignId:project_tasks|required',
            'employee_id' => 'foreignId:employees|required',
            'log_date' => 'date|required',
            'hours' => 'decimal:8,2|required',
            'description' => 'text|nullable',
        ],
    ],
    'tickets' => [
        'model' => 'Ticket',
        'table' => 'tickets',
        'route' => 'tickets',
        'prefix' => 'support',
        'sidebar' => ['group' => 'Support', 'icon' => 'lifebuoy', 'label' => 'Tickets'],
        'permission' => 'tickets',
        'status_enum' => 'TicketStatus',
        'fields' => [
            'reference_number' => 'string|unique|required',
            'contact_id' => 'foreignId:contacts|nullable',
            'subject' => 'string|required',
            'priority' => 'string|default:medium',
            'status' => 'string|default:open',
            'description' => 'text|nullable',
        ],
    ],
    'knowledge-base' => [
        'model' => 'KnowledgeBaseArticle',
        'table' => 'knowledge_base_articles',
        'route' => 'knowledge-base',
        'prefix' => 'support',
        'sidebar' => ['group' => 'Support', 'icon' => 'book-open', 'label' => 'Knowledge base'],
        'permission' => 'knowledge-base',
        'fields' => [
            'title' => 'string|required',
            'slug' => 'string|unique|required',
            'category' => 'string|required',
            'content' => 'text|required',
            'is_published' => 'boolean|default:false',
        ],
    ],

    // Batch 7 — Retail & Operations
    'supplier-evaluations' => [
        'model' => 'SupplierEvaluation',
        'table' => 'supplier_evaluations',
        'route' => 'supplier-evaluations',
        'prefix' => 'purchasing',
        'sidebar' => ['group' => 'Purchasing', 'icon' => 'star', 'label' => 'Supplier evaluations'],
        'permission' => 'supplier-evaluations',
        'fields' => [
            'contact_id' => 'foreignId:contacts|required',
            'evaluation_date' => 'date|required',
            'quality_score' => 'integer|default:0',
            'delivery_score' => 'integer|default:0',
            'price_score' => 'integer|default:0',
            'overall_score' => 'integer|default:0',
            'comments' => 'text|nullable',
        ],
    ],
    'floor-plans' => [
        'model' => 'FloorPlan',
        'table' => 'floor_plans',
        'route' => 'floor-plans',
        'prefix' => 'warehouse',
        'sidebar' => ['group' => 'Warehouse', 'icon' => 'map-pin', 'label' => 'Floor plans'],
        'permission' => 'floor-plans',
        'fields' => [
            'name' => 'string|required',
            'warehouse_id' => 'foreignId:warehouses|required',
            'branch_id' => 'foreignId:branches|nullable',
            'width' => 'integer|nullable',
            'height' => 'integer|nullable',
            'layout_data' => 'json|nullable',
            'is_active' => 'boolean|default:true',
        ],
    ],
    'stock-transfers' => [
        'model' => 'StockTransfer',
        'table' => 'stock_transfers',
        'route' => 'stock-transfers',
        'prefix' => 'warehouse',
        'sidebar' => ['group' => 'Warehouse', 'icon' => 'arrows-right-left', 'label' => 'Stock transfers'],
        'permission' => 'stock-transfers',
        'status_enum' => 'StockTransferStatus',
        'fields' => [
            'reference_number' => 'string|unique|required',
            'product_id' => 'foreignId:products|required',
            'from_warehouse_id' => 'foreignId:warehouses|required',
            'to_warehouse_id' => 'foreignId:warehouses|required',
            'quantity' => 'integer|required',
            'transfer_date' => 'date|required',
            'status' => 'string|default:draft',
            'notes' => 'text|nullable',
        ],
    ],

];
