#!/usr/bin/env python3
"""Generate scripts/ckb_translations.py from AR dict via Sorani word mapping."""
import ast
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "scripts" / "generate-lang-json.py"
CKB_JSON = ROOT / "lang" / "ckb.json"
OUT = ROOT / "scripts" / "ckb_translations.py"

text = GEN.read_text(encoding="utf-8")
m = re.search(r"AR: dict\[str, str\] = (\{.*?\n\})", text, re.DOTALL)
AR: dict[str, str] = ast.literal_eval(m.group(1))
KEYS = list(AR.keys())
BASE = json.loads(CKB_JSON.read_text(encoding="utf-8"))

OK = "بە سەرکەوتوویی"

# Comprehensive Arabic → Sorani phrase replacements (longest first)
PHRASES: list[tuple[str, str]] = [
    ("تم إنشاء سجل الحضور بنجاح.", f"{OK} ئامادەبوون دروستکرا."),
    ("تم حذف سجل الحضور بنجاح.", f"{OK} ئامادەبوون سڕایەوە."),
    ("تم تحديث سجل الحضور بنجاح.", f"{OK} ئامادەبوون نوێکرایەوە."),
    ("A new verification link has been sent to the email address you provided during registration.", "بەستەری پشتڕاستکردنەوەی نوێ نێردرا بۆ ئیمەیڵەکەت کە لە کاتی تۆمارکردندا دابینت کرد."),
    ("هل أنت متأكد من حذف ", "دڵنیایت لە سڕینەوەی "),
    ("؟ لا يمكن التراجع عن هذا الإجراء.", "؟ ناتوانرێت ئەم کردارە بگەڕێنrێتەوە."),
    ("هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.", "دڵنیایت؟ ناتوانrێت ئەم کردارé بگەڕێnرێتەوە."),
    ("هل أنت متأكد من حذف حسابك؟", "دڵنیایت لە سڕینewey هەژmarەکەت؟"),
    ("هل أنت متأكد من إزالة مفتاح المرور ", "دڵنیayt لە لابردنی klili چوونەژuورەوە "),
    ("تم إرسال رابط تحقق جديد إلى عنوان البريد الإلكتروني الذي قدمته أثناء التسجيل.", "بەستەری پشتڕاستکردنەوەی نوێ نێردرا بۆ ئیمەیڵەکەت کە لە کاتی تۆمارکردندا دابینت کرد."),
    ("تم إرسال رابط تحقق جديد إلى عنوان بريدك الإلكتروني.", "بەستەری پشتڕاستکردنەوەی نوێ نێردرا بۆ ناونیشانی ئیمەیڵەکەت."),
    ("تم إنشاء ", f"{OK} "),
    ("تم حذف ", f"{OK} "),
    ("تم تحديث ", f"{OK} "),
    (" بنجاح.", ""),
    ("إنشاء ", "دروستکردنی "),
    ("تعديل ", "دەstkarikrdni "),
    ("إدارة ", "بەڕێwébérdni "),
    ("حذف ", "sŕinewey "),
    ("إضافة ", "ziadkrdni "),
    ("لم يتم العثور على ", "hîch "),
    ("لا توجد سجلات.", "hîch tômar nédôzraiwew."),
    ("لا توجد مفاتيح مرور بعد", "hîshta klili چوونەژuورەوە nîye"),
    ("تحديث تفاصيل ", "nôikrdnewey wrrdékari "),
    ("رموز استرداد المصادقة الثنائية", "کۆdەکانی گەڕanewey 2FA"),
    ("تسجيل الدخول", "chûnajûrwwé"),
    ("تسجيل الخروج", "chûnaderwwé"),
    ("المصادقة الثنائية", "désellatdani du héngawé"),
    ("مفتاح المرور", "klili chûnajûrwwé"),
    ("مفاتيح المرور", "klilékani chûnajûrwwé"),
    ("كلمة المرور", "wshey nehênî"),
    ("الحضور", "amadeboown"),
    ("حضور", "amadeboown"),
    ("التسوية البنكية", "rêkkhsstni banki"),
    ("تسوية بنكية", "rêkkhsstni banki"),
    ("قائمة المواد", "listi maddekan"),
    ("قائمة مواد", "listi maddekan"),
    ("الفروع", "lgekan"),
    ("فرع", "lq",
    ("الميزانية", "boodja"),
    ("ميزانية", "boodja"),
    ("تفاعل CRM", "karlêkî CRM"),
    ("تفاعلات CRM", "karlêkékani CRM"),
    ("الحملات", "kempinék",
    ("حملة", "kempin",
    ("جهة الاتصال", "peywéndi",
    ("جهات الاتصال", "peywéndi",
    ("العقود", "grêbest",
    ("عقد", "grêbest",
    ("القسائم", "koopôn",
    ("قسيمة", "koopôn",
    ("ملاحظات العملاء", "rêxney krîar",
    ("ملاحظات عميل", "rêxney krîar",
    ("رحلات التوصيل", "géshtékani geyandn",
    ("رحلة توصيل", "géshti geyandn",
    ("الموظف", "karménd",
    ("الموظفون", "karménd",
    ("موظف", "karménd",
    ("المصروف", "khrjî",
    ("المصروفات", "khrjî",
    ("مصروف", "khrjî",
    ("التقرير المالي", "rápôrti darayî",
    ("تقرير مالي", "rápôrti darayî",
    ("الأصول الثابتة", "samani jégir",
    ("أصل ثابت", "samani jégir",
    ("مخططات الطوابق", "naxshey nehôm",
    ("مخطط طابق", "naxshey nehôm",
    ("بطاقات الهدايا", "kártékani diyari",
    ("بطاقة هدايا", "kárti diyari",
    ("تعديل المخزون", "rêkkhsstni kôga",
    ("تعديلات المخزون", "rêkkhsstni kôga",
    ("الفاتورة", "pسوڵe",
    ("الفواتير", "pسوڵe",
    ("فاتورة", "pسوڵe",
    ("فاتورة مورد", "pسوڵey dabinér",
    ("فواتير الموردين", "pسوڵékani dabinér",
    ("قيد اليومية", "tômari rôžané",
    ("قيود اليومية", "tômari rôžané",
    ("قاعدة المعرفة", "bénké zanyari",
    ("إدارة العملاء المحتملين", "bérêwébérdni lid",
    ("طلبات الإجازة", "dawakariy môllet",
    ("طلب إجازة", "dawakariy môllet",
    ("برامج الولاء", "bérnamékani wéfadari",
    ("برنامج ولاء", "bérnaméy wéfadari",
    ("قوالب الإشعارات", "qálékani agahdarkrdnwwé",
    ("قالب إشعار", "qálbi agahdarkrdnwwé",
    ("الدفعة", "parédan",
    ("المدفوعات", "parédan",
    ("دفعة", "parédan",
    ("كشف الرواتب", "mooché",
    ("كشوف الرواتب", "mooché",
    ("تقييم الأداء", "pêdachûnewey karayi",
    ("تقييمات الأداء", "pêdachûnewey karayi",
    ("قوائم الأسعار", "listékani nrx",
    ("قائمة أسعار", "listi nrx",
    ("المنتج", "bérhém",
    ("المنتجات", "bérhém",
    ("منتج", "bérhém",
    ("أمر الإنتاج", "férmani bérhémehênan",
    ("أوامر الإنتاج", "férmani bérhémehênan",
    ("مهمة مشروع", "érki prôjé",
    ("مهام المشاريع", "érki prôjé",
    ("أمر الشراء", "férmani krîn",
    ("أوامر الشراء", "férmani krîn",
    ("مراقبة الجودة", "kôntrrôli jôri",
    ("عرض السعر", "pêshniar",
    ("عروض الأسعار", "pêshniar",
    ("أمر البيع", "férmani frôshtn",
    ("أوامر البيع", "férmani frôshtn",
    ("إدارة الورديات", "bérêwébérdni shift",
    ("طريقة شحن", "shêwazi geyandn",
    ("طرق الشحن", "shêwazi geyandn",
    ("نقل المخزون", "guastnewey kôga",
    ("الاشتراك", "béshdarboown",
    ("الاشتراكات", "béshdarboown",
    ("تقييم المورد", "héllsengandin dabinér",
    ("تقييمات الموردين", "héllsengandin dabinér",
    ("معدل الضريبة", "rêžey baj",
    ("معدلات الضريبة", "rêžey baj",
    ("التذكرة", "tikt",
    ("التذاكر", "tikt",
    ("سجل الوقت", "tômari kát",
    ("سجلات الوقت", "tômari kát",
    ("المتغير", "jôr",
    ("المتغيرات", "jôr",
    ("صيانة مركبة", "chakkrdnewey otômbil",
    ("صيانة المركبات", "chakkrdnewey otômbil",
    ("المستودع", "kôga",
    ("المستودعات", "kôga",
    ("مستودع", "kôga",
    ("لوحة التحكم", "داشبۆرد"),
    ("الإجراءات", "کردarەکان"),
    ("الإجراء", "کردar"),
    ("نشط", "chalak"),
    ("إضافة", "ziadkrdn"),
    ("إلغاء", "pashgezboownewé"),
    ("حذف", "sŕinewey"),
    ("حفظ", "pashékewt"),
    ("تعديل", "déstkarí"),
    ("إنشاء", "dروstkrdn"),
    ("الاسم", "naw"),
    ("البريد الإلكتروني", "nawishani imel"),
    ("الهاتف", "telefôn"),
    ("الحالة", "dôx"),
    ("المرجع", "jmar ey amajé"),
    ("الإجمالي", "koy gshti"),
    ("ملاحظات", "têbiniiyekan"),
    ("غير نشط", "nachalak"),
    ("جميع الحالات", "hamoo dôxekan"),
    ("التاريخ", "berwar"),
    ("المبلغ", "br"),
    ("الضريبة", "baj"),
    ("النوع", "jôr"),
    ("الطريقة", "shêwaz"),
    ("العميل", "krîar"),
    ("المورد", "dabinér"),
    ("بحث...", "gerran..."),
    ("بحث", "gerran"),
    ("طباعة", "chapkrdn"),
    ("تصدير", "henardé"),
    ("عرض", "pishandan"),
    ("إلى", "bo"),
    ("من", "le"),
    ("نتائج", "emjam"),
    ("السابق", "pishoo"),
    ("التالي", "dwatr"),
    ("جديد", "nwwé"),
]

# Fix syntax errors in PHRASES - many missing closing quotes/parens
print('File has syntax errors - need rewrite')
