# Sorani manual translations for keys not covered by patterns.
MANUAL: dict[str, str] = {
    "2FA recovery codes": "کۆدەکانی گەڕانەوەی 2FA",
    "A new verification link has been sent to the email address you provided during registration.": "بەستەری پشتڕاستکردنەوەی نوێ نێردرا بۆ ئیمەیڵەکەت کە لە کاتی تۆمارکردندا دابینت کرد.",
    "A new verification link has been sent to your email address.": "بەستەری پشتڕاستکردنەوەی نوێ نێردرا بۆ ناونیشانی ئیمەیڵەکەت.",
    "Action": "کردار",
    "Actions": "کردارەکان",
    "Active": "چالاک",
    "Add": "زیادکردن",
    "Add a new customer or supplier": "زیادکردنی کڕیار یان دابینکەرێکی نوێ",
    "Add a new employee record": "زیادکردنی تۆماری کارمەندێکی نوێ",
    "Add a new product to your inventory": "زیادکردنی بەرهەمێکی نوێ بۆ کۆگاکەت",
    "Add a new storage location": "زیادکردنی شوێنی کۆگای نوێ",
    "Add a new tax rate": "زیادکردنی ڕێژەی باجێکی نوێ",
    "Add a passkey to sign in without a password": "کلیلی چوونەژوورەوە زیاد بکە بۆ چوونەژوورەوە بەبێ وشەی نهێنی",
    "Add passkey": "زیادکردنی کلیلی چوونەژوورەوە",
    "Added :time": "زیادکرا :time",
    "Address": "ناونیشان",
    "Adjustment date": "بەرواری ڕێکخستن",
    "All actions": "هەموو کردارەکان",
    "All report types": "هەموو جۆرەکانی ڕاپۆرت",
    "All statuses": "هەموو دۆخەکان",
    "All types": "هەموu جۆrەکان",
    "Allocated Amount": "بڕی تەرخانکراو",
    "Amount": "بڕ",
    "Appearance": "ڕووکار",
    "Appearance settings": "ڕێکخستنەکانی ڕووکار",
    "Are you sure you want to delete this CRM interaction? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم کارلێکی CRM؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this bill? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم پسوڵەی دابینکەر؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this contact? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم پەیوەندییە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this employee? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم کارمەندە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this expense? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم خرجییە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this financial report? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم ڕاپۆرتی دارایی؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this inventory adjustment? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم ڕێکخستنی کۆگا؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this invoice? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم پسوڵەیە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this journal entry? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم تۆmاری ڕۆژanە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this payment? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم پارەدانە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this payroll? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم مووچەیە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this product?": "دڵنیایت لە سڕینەوەی ئەم بەرhەمە؟",
    "Are you sure you want to delete this product? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم بەرhەمە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this purchase order? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم فەرmani کڕin؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this quotation? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم پێshniarە؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this sale order? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم فەرmani فرۆshtn؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this tax rate? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم ڕێژey baj؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete this warehouse? This action cannot be undone.": "دڵنیایت لە سڕینەوەی ئەم کۆga؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
    "Are you sure you want to delete your account?": "دڵنیایت لە سڕینەوەی هەژmarەکەت؟",
    "Are you sure you want to remove the passkey ": "دڵنیایت لە لابردنی klili چوونەژuورەوە ",
    "Are you sure? This action cannot be undone.": "دڵنیایت؟ ناتوانrێت ئەم کردارە بگەڕێnrێتەوە.",
}
