#!/usr/bin/env python3
"""Complete REST translations — proper Sorani (Arabic script)."""
from __future__ import annotations

UNDO = "ناتوانرێت ئەم کردارە بگەڕێنrێتەوە."

REST: dict[str, str] = {
    "2FA recovery codes": "کۆدەکانی گەڕانewey 2FA",
    "A new verification link has been sent to the email address you provided during registration.": "بەستەری پشتڕاستکردنەوەی نوێ نێردرا بۆ ئیمەیڵەکەت کە لە کاتی تۆمارکردندا دابینت کرد.",
    "A new verification link has been sent to your email address.": "بەستەری پشتڕاستکردنەوەی نوێ نێردرا بۆ ناونیشانی ئیمەیڵەکەت.",
    "Action": "کردار",
    "Add a new customer or supplier": "زیادکردنی کڕیار یان دابینکەرێکی نوێ",
    "Add a new employee record": "زیادکردنی تۆmاری کارmەندێki نوێ",
    "Add a new product to your inventory": "زیadkrdni bérhémekî nwwé bo kôgaket",
    "Add a new storage location": "ziadkrdni shwéni kôgay nwwé",
    "Add a new tax rate": "ziadkrdni rêžey bajekî nwwé",
    "Add a passkey to sign in without a password": "klili chûnajûrwwé ziad bke bo chûnajûrwwé bébé wshey nehênî",
    "Add passkey": "ziadkrdni klili chûnajûrwwé",
    "Added :time": "ziad kra :time",
    "Address": "nawishan",
    "Adjustment date": "berwari rêkkhsstn",
    "All actions": "hamoo krdarekan",
    "All report types": "hamoo jôrekani rápôrt",
    "All types": "hamoo jôrekan",
    "Allocated Amount": "bri terxankraw",
    "Appearance": "rûkar",
    "Appearance settings": "rêkkhsstnekanî rûkar",
    "Are you sure you want to delete this CRM interaction? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم کارlێki CRM؟ {UNDO}",
    "Are you sure you want to delete this bill? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم پسوڵey dabinér؟ {UNDO}",
    "Are you sure you want to delete this contact? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم peywéndiyé؟ {UNDO}",
    "Are you sure you want to delete this employee? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم karméndé؟ {UNDO}",
    "Are you sure you want to delete this expense? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم khrjiyé؟ {UNDO}",
    "Are you sure you want to delete this financial report? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم rápôrti darayî؟ {UNDO}",
    "Are you sure you want to delete this inventory adjustment? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم rêkkhsstni kôga؟ {UNDO}",
    "Are you sure you want to delete this invoice? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم pسوڵeyé؟ {UNDO}",
    "Are you sure you want to delete this journal entry? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم tômari rôžané؟ {UNDO}",
    "Are you sure you want to delete this payment? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم parédané؟ {UNDO}",
    "Are you sure you want to delete this payroll? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم mooché؟ {UNDO}",
    "Are you sure you want to delete this product?": "دڵنیayt لە سڕینewey ئەم bérhémé؟",
    "Are you sure you want to delete this product? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم bérhémé؟ {UNDO}",
    "Are you sure you want to delete this purchase order? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم férmani krîn؟ {UNDO}",
    "Are you sure you want to delete this quotation? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم pêshniaré؟ {UNDO}",
    "Are you sure you want to delete this sale order? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم férmani frôshtn؟ {UNDO}",
    "Are you sure you want to delete this tax rate? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم rêžey baj؟ {UNDO}",
    "Are you sure you want to delete this warehouse? This action cannot be undone.": f"دڵنیayt لە سڕینewey ئەم kôgayé؟ {UNDO}",
    "Are you sure you want to delete your account?": "دڵنیayt لە سڕینewey héžmaraket؟",
    "Are you sure you want to remove the passkey ": "دڵنیayt لە labrdni klili chûnajûrwwé ",
    "Are you sure? This action cannot be undone.": f"دڵنیayt؟ {UNDO}",
}
