MANUAL: dict[str, str] = {
    '2FA recovery codes': 'کۆدەکانی گەڕانەوەی ٢FA',
    'A new verification link has been sent to the email address you provided during registration.': 'بەستەرێکی پشتڕاستکردنەوەی نوێ نێردرا بۆ ئیمەیڵی لە کاتی تۆمارکردندا دابینت کرد.',
    'A new verification link has been sent to your email address.': 'بەستەرێکی پشتڕاستکردنەوەی نوێ نێردرا بۆ ئیمەیڵەکەت.',
    'Action': 'کردار',
    'Add a new customer or supplier': 'زیادکردنی کڕیار یان دابینکەرێکی نوێ',
    'Add a new employee record': 'زیادکردنی تۆماری کارمەندێکی نوێ',
    'Add a new product to your inventory': 'زیادکردنی بەرهەمێکی نوێ بۆ کۆگاکەت',
    'Add a new storage location': 'زیادکردنی شوێنی هەڵگرتنێکی نوێ',
    'Add a new tax rate': 'زیادکردنی ڕێژەی باجێکی نوێ',
    'Add a passkey to sign in without a password': 'کلیلی چوونەژوورەوەیەک زیاد بکە بۆ چوونەژوورەوە بەبێ وشەی نهێنی',
    'Add passkey': 'زیادکردنی کلیلی چوونەژوورەوە',
    'Added :time': 'زیادکرا :time',
    'Address': 'ناونیشان',
    'Adjustment date': 'بەرواری ڕێکخستن',
    'All actions': 'هەموو کردارەکان',
    'All report types': 'هەموو جۆرەکانی ڕاپۆرت',
    'All types': 'هەموو جۆرەکان',
    'Allocated Amount': 'بڕی تەرخانکراو',
    'Appearance': 'ڕواڵەت',
    'Appearance settings': 'ڕێکخستنەکانی ڕواڵەت',
    'Are you sure you want to delete this CRM interaction? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم کارلێکی CRM بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this bill? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم پسوڵەی دابینکەرە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this contact? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم پەیوەندییە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this employee? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم کارمەندە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this expense? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم خرجییە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this financial report? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم ڕاپۆرتی داراییە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this inventory adjustment? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم ڕێکخستنی کۆگایە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this invoice? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم پسوڵەیە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this journal entry? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم تۆماری ڕۆژانەیە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this payment? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم پارەدانە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this payroll? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم مووچەیە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this product?': 'دڵنیایت دەتەوێت ئەم بەرهەمە بسڕیتەوە؟',
    'Are you sure you want to delete this product? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم بەرهەمە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this purchase order? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم فەرمانی کڕینە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this quotation? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم پێشنیارە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this sale order? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم فەرمانی فرۆشتنە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this tax rate? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم ڕێژەی باجە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete this warehouse? This action cannot be undone.': 'دڵنیایت دەتەوێت ئەم کۆگایە بسڕیتەوە؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Are you sure you want to delete your account?': 'دڵنیایت دەتەوێت هەژمارەکەت بسڕیتەوە؟',
    'Are you sure you want to remove the passkey ': 'دڵنیایت دەتەوێت کلیلی چوونەژوورەوە بسڕیتەوە ',
    'Are you sure? This action cannot be undone.': 'دڵنیایت؟ ناتوانرێت ئەم کردارە بگەڕێنرێتەوە.',
    'Asset Code': 'کۆدی سامان',
    'Attendance': 'ئامادەبوون',
    'Attendance Date': 'بەرواری ئامادەبوون',
    'Audit logs': 'تۆمارەکانی پشکنین',
    'Authenticating...': 'پشتڕاستکردنەوە...',
    'Authentication code': 'کۆدی پشتڕاستکردنەوە',
    'Back': 'گەڕانەوە',
    'Bank Name': 'ناوی بانک',
    'Bank reconciliation': 'ڕێکخستنی بانکی',
    'Barcode': 'بارکۆد',
    'Base Cost': 'تێچووی بنەڕەت',
    'Bill date': 'بەرواری پسوڵە',
    'Bill of materials': 'لیستی ماددەکان',
    'Billing Cycle': 'سووڕی پارەدان',
    'Bills': 'پسوڵەکانی دابینکەر',
    'Body': 'ناوەڕۆک',
    'Book Demo': 'حجزکردنی نموونە',
    'Branch Id': 'ناسنامەی لق',
    'Branches': 'لقەکان',
    'Budget': 'بودجە',
    'Budgeting': 'بودجە',
    'Bulk actions': 'کردارە کۆمەڵییەکان',
    'CRM interactions': 'کارلێکەکانی CRM',
    'Campaigns': 'کەمپینەکان',
    'Carrier': 'گەیاندنکار',
    'Channel': 'کەناڵ',
    'Check In': 'تۆمارکردنی هاتن',
    'Check Out': 'تۆمارکردنی چوون',
    'Click here to re-send the verification email.': 'لێرە کلیک بکە بۆ دووبارە ناردنی ئیمەیڵی پشتڕاستکردنەوە.',
    'Close': 'داخستن',
    'Closing Balance': 'باڵانسی کۆتایی',
    'Code': 'کۆد',
    'Comments': 'لێدوانەکان',
    'Company': 'کۆمپانیا',
    'Company name': 'ناوی کۆمپانیا',
    'Component Product Id': 'ناسنامەی بەرهەمی پێکهاتە',
    'Configure tax rates for billing and accounting': 'ڕێکخستنی ڕێژەکانی باج بۆ پارەدان و ژمێریاری',
    'Confirm': 'پشتڕاستکردنەوە',
    'Confirm password': 'پشتڕاستکردنەوەی وشەی نهێنی',
    'Contact': 'پەیوەندی',
    'Contact Id': 'ناسنامەی پەیوەندی',
    'Contacts': 'پەیوەندییەکان',
    'Content': 'ناوەڕۆک',
    'Continue': 'بەردەوامبوون',
    'Contract Id': 'ناسنامەی گرێبەست',
    'Contracts': 'گرێبەستەکان',
    'Cost': 'تێچوو',
    'Coupons': 'کووپۆنەکان',
    'Create': 'دروستکردن',
    'Create and manage customer price quotes': 'دروستکردن و بەڕێوەبردنی پێشنیارەکانی نرخی کڕیار',
    'Created': 'دروستکراو',
    'Credit': 'قەرزدار',
    'Currency': 'دراو',
    'Current Balance': 'باڵانسی ئێستا',
    'Current Value': 'نرخی ئێستا',
    'Current password': 'وشەی نهێنی ئێستا',
    'Customer feedback': 'ڕەخنەی کڕیار',
    'Dark': 'تاریک',
    'Debit': 'قەرزخواز',
    'Deductions': 'لێبڕینەکان',
    'Delete your account and all of its resources': 'سڕینەوەی هەژمارەکەت و هەموو سەرچاوەکانی',
    'Deleted': 'سڕدراوە',
    'Delivery Score': 'نمرەی گەیاندن',
    'Delivery date': 'بەرواری گەیاندن',
    'Delivery trips': 'گەشتەکانی گەیاندن',
    'Department': 'بەش',
    'Description': 'وەسف',
    'Disable 2FA': 'ناچالاککردنی ٢FA',
    'Discount Type': 'جۆری داشکاندن',
    'Discount Value': 'نرخی داشکاندن',
    'Documentation': 'بەڵگەنامە',
    'Driver Name': 'ناوی شۆفێر',
    'Due Date': 'بەرواری موعد',
    'Due date': 'بەرواری موعد',
    'Each recovery code can be used once to access your account and will be removed after use. If you need more, click Regenerate codes above.': 'هەر کۆدێکی گەڕانەوەیەک جارێک دەتوانرێت بەکاربهێنرێت بۆ چوونەژوورەوە بۆ هەژمارەکەت و دوای بەکارهێنان دەسڕدرێتەوە. ئەگەر زیاترت پێویستە، لە سەرەوە دووبارە دروستکردنی کۆدەکان کلیک بکە.',
    'Email address': 'ناونیشانی ئیمەیڵ',
    'Email password reset link': 'ناردنی بەستەری نوێکردنەوەی وشەی نهێنی بە ئیمەیڵ',
    'Email verification': 'پشتڕاستکردنەوەی ئیمەیڵ',
    'Employee': 'کارمەند',
    'Employee Id': 'ناسنامەی کارمەند',
    'Employee number': 'ژمارەی کارمەند',
    'Employees': 'کارمەندان',
    'Enable 2FA': 'چالاککردنی ٢FA',
    'Enable two-factor authentication': 'چالاککردنی پشتڕاستکردنەوەی دوو هەنگاوە',
    'End Date': 'بەرواری کۆتایی',
    'End Time': 'کاتی کۆتایی',
    'Ensure your account is using a long, random password to stay secure': 'دڵنیابە لەوەی هەژمارەکەت وشەی نهێنییەکی درێژ و هەڕەمەکی بەکاردەهێنێت بۆ پاراستن',
    'Enter the 6-digit code from your authenticator app.': 'کۆدی ٦ ژمارەیی لە ئەپلیکەیشنی پشتڕاستکەرەوە بنووسە.',
    'Enter the authentication code provided by your authenticator application.': 'کۆدی پشتڕاستکردنەوە بنووسە کە لە ئەپلیکەیشنی پشتڕاستکەرەوەتەوە دابینکراوە.',
    'Enter your email and password below to log in': 'ئیمەیڵ و وشەی نهێنی لە خوارەوە بنووسە بۆ چوونەژوورەوە',
    'Enter your email to receive a password reset link': 'ئیمەیڵەکەت بنووسە بۆ وەرگرتنی بەستەری نوێکردنەوەی وشەی نهێنی',
    'Entry date': 'بەرواری تۆمار',
    'Estimated Value': 'نرخی مەزەندەکراو',
    'Evaluation Date': 'بەرواری هەڵسەنگاندن',
    'Expected date': 'بەرواری چاوەڕوانکراو',
    'Expense date': 'بەرواری خرجی',
    'Expenses': 'خرجییەکان',
    'Expires At': 'بەسەردەچێت لە',
    'Export CSV': 'هەناردەی CSV',
    'Export Excel': 'هەناردەی Excel',
    'Export PDF': 'هەناردەی PDF',
    'Failed Quantity': 'بڕی شکستخواردوو',
    'Feedback': 'ڕەخنە',
    'Feedback Date': 'بەرواری ڕەخنە',
    'Filter': 'پاڵاوتن',
    'Filters': 'پاڵاوتنەکان',
    'Financial reports': 'ڕاپۆرتە داراییەکان',
    'First name': 'ناوی یەکەم',
    'Fixed assets': 'سامانی جێگیر',
    'Floor plans': 'نەخشەکانی نهۆم',
    'Follow-up date': 'بەرواری بەدواداچوون',
    'Forgot password': 'وشەی نهێنی لەبیرچوو',
    'Forgot your password?': 'وشەی نهێنیت لەبیرچووە؟',
    'From Warehouse Id': 'ناسنامەی کۆگای سەرچاوە',
    'Generate a new financial report': 'دروستکردنی ڕاپۆرتێکی داراییی نوێ',
    'Generate and review profit, balance, and cash flow reports': 'دروستکردن و پێداچوونەوە بە ڕاپۆرتەکانی قازانج، باڵانس و ڕەوتی پارە',
    'Gift cards': 'کارتەکانی دیاری',
    'Give this passkey a name to help you identify it later.': 'ناوێک بۆ ئەم کلیلی چوونەژوورەوە بدە بۆ ئەوەی دواتر بتوانیت بیاناسیت.',
    'Gross': 'کۆی گشتی',
    'Gross amount': 'بڕی کۆی گشتی',
    'Height': 'بەرزایی',
    'Hide recovery codes': 'شاردنەوەی کۆدەکانی گەڕانەوە',
    'Hire date': 'بەرواری دامەزراندن',
    'Hours': 'کاتژمێر',
    'IP address': 'ناونیشانی IP',
    'Initial Balance': 'باڵانسی سەرەتایی',
    'Inspection Date': 'بەرواری پشکنین',
    'Interaction date': 'بەرواری کارلێک',
    'Interaction type': 'جۆری کارلێک',
    'Inventory adjustments': 'ڕێکخستنەکانی کۆگا',
    'Invoice date': 'بەرواری پسوڵە',
    'Invoices': 'پسوڵەکان',
    'Is Active': 'چالاکە',
    'Is Published': 'بڵاوکراوەتەوە',
    'JSON': 'JSON',
    'Job title': 'ناونیشانی کار',
    'Journal entries': 'تۆمارەکانی ڕۆژانە',
    'Knowledge base': 'بنکەی زانیاری',
    'Last name': 'ناوی کۆتایی',
    'Last used :time': 'دوایین بەکارهێنان :time',
    'Layout Data': 'زانیاری نەخشە',
    'Lead management': 'بەرێوەبردنی لید',
    'Leave Type': 'جۆری مۆلەت',
    'Leave requests': 'داواکارییەکانی مۆلەت',
    'Light': 'ڕووناک',
    'Log Date': 'بەرواری تۆمار',
    'Log a new customer interaction': 'تۆمارکردنی کارلێکی نوێی کڕیار',
    'Log in': 'چوونەژوورەوە',
    'Log in to your account': 'چوونەژوورەوە بۆ هەژمارەکەت',
    'Log out': 'چوونەدەرەوە',
    'Low stock': 'کۆگای کەم',
    'Loyalty programs': 'بەرنامەکانی وفاداری',
    'Maintenance Date': 'بەرواری چاککردنەوە',
    'Maintenance Type': 'جۆری چاککردنەوە',
    'Manage customer billing and receivables': 'بەڕێوەبردنی پارەدان و قەرزەکانی کڕیار',
    'Manage customer orders and outgoing sales': 'بەڕێوەبردنی داواکارییەکانی کڕیار و فرۆشتنە دەرچووەکان',
    'Manage customers and suppliers across your business': 'بەڕێوەبردنی کڕیار و دابینکەر لە سەرانسەری کارەکەت',
    'Manage general ledger journal entries': 'بەڕێوەبردنی تۆمارەکانی ڕۆژانەی ژمێریاری گشتی',
    'Manage products and inventory levels': 'بەڕێوەبردنی بەرهەم و ئاستی کۆگا',
    'Manage staff records and employment details': 'بەڕێوەبردنی تۆمارەکانی کارمەند و وردەکارییەکانی دامەزراندن',
    'Manage storage locations and inventory hubs': 'بەڕێوەبردنی شوێنەکانی هەڵگرتن و ناوەندەکانی کۆگا',
    'Manage supplier bills and payables': 'بەڕێوەبردنی پسوڵە و قەرزەکانی دابینکەر',
    'Manage your passkeys for passwordless sign-in': 'بەڕێوەبردنی کلیلەکانی چوونەژوورەوەت بۆ چوونەژوورەوە بەبێ وشەی نهێنی',
    'Manage your profile and account settings': 'بەڕێوەبردنی پرۆفایل و ڕێکخستنەکانی هەژمارەکەت',
    'Manage your two-factor authentication settings': 'بەڕێوەبردنی ڕێکخستنەکانی پشتڕاستکردنەوەی دوو هەنگاوەت',
    'Min. level': 'کەمترین ئاست',
    'Minimum stock level': 'کەمترین ئاستی کۆگا',
    'Model': 'مۆدێل',
    'Net': 'پوخت',
    'Net amount': 'بڕی پوخت',
    'New password': 'وشەی نهێنی نوێ',
    'No': 'نەخێر',
    'None': 'هیچ',
    'Notification templates': 'قالبەکانی ئاگاداری',
    'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.': 'کاتێک هەژمارەکەت دەسڕدرێتەوە، هەموو سەرچاوە و زانیارییەکانی بە تەواوی دەسڕدرێنەوە. تکایە وشەی نهێنی بنووسە بۆ پشتڕاستکردنەوەی سڕینەوەی هەمیشەیی هەژمارەکەت.',
    'Opening Balance': 'باڵانسی سەرەتا',
    'Opening balance': 'باڵانسی سەرەتا',
    'Or continue with email': 'یان بەردەوامبە بە ئیمەیڵ',
    'Or, return to': 'یان، بگەڕێوە بۆ',
    'Overall Score': 'نمرەی گشتی',
    'Passed Quantity': 'بڕی سەرکەوتوو',
    'Passkey name': 'ناوی کلیلی چوونەژوورەوە',
    'Passkeys': 'کلیلەکانی چوونەژوورەوە',
    'Passkeys are not supported in this browser.': 'کلیلەکانی چوونەژوورەوە لەم وێبگەڕەدا پشتگیری ناکرێن.',
    'Password': 'وشەی نهێنی',
    'Password updated.': 'وشەی نهێنی نوێکرایەوە.',
    'Pay period': 'ماوەی مووچە',
    'Pay period end': 'کۆتایی ماوەی مووچە',
    'Pay period start': 'دەستپێکی ماوەی مووچە',
    'Payment date': 'بەرواری پارەدان',
    'Payments': 'پارەدانەکان',
    'Payrolls': 'مووچەکان',
    'Performance reviews': 'پێداچوونەوەکانی کارایی',
    'Period': 'ماوە',
    'Period End': 'کۆتایی ماوە',
    'Period Start': 'دەستپێکی ماوە',
    'Period end': 'کۆتایی ماوە',
    'Period start': 'دەستپێکی ماوە',
    'Plan Name': 'ناوی پلان',
    'Platform': 'پلاتفۆرم',
    'Please confirm access to your account by entering one of your emergency recovery codes.': 'تکایە چوونەژوورەوە بۆ هەژمارەکەت پشتڕاست بکەرەوە بە نووسینی یەکێک لە کۆدەکانی گەڕانەوەی فریاکەوتن.',
    'Please enter your new password below': 'تکایە وشەی نهێنی نوێ لە خوارەوە بنووسە',
    'Please verify your email address by clicking on the link we just emailed to you.': 'تکایە ناونیشانی ئیمەیڵەکەت پشتڕاست بکەرەوە بە کلیککردن لەسەر بەستەرەکە کە ئێستا ناردمان.',
    'Points Per Currency': 'خاڵ بۆ هەر دراوێک',
    'Positive values indicate receivable (they owe you). Negative values indicate payable (you owe them).': 'نرخە ئەرێنییەکان قەرزی وەرگیراو دەردەخەن (ئەوان قەرزدارن). نرخە نەرێنییەکان قەرزی دراو دەردەخەن (تۆ قەرزداری).',
    'Price Score': 'نمرەی نرخ',
    'Price lists': 'لیستەکانی نرخ',
    'Priority': 'پێشەنگی',
    'Process employee pay periods and compensation': 'پرۆسەکردنی ماوەکانی مووچە و قەرەبووی کارمەند',
    'Product': 'بەرهەم',
    'Product Id': 'ناسنامەی بەرهەم',
    'Production Order Id': 'ناسنامەی فەرمانی بەرهەمھێنان',
    'Production orders': 'فەرمانەکانی بەرهەمھێنان',
    'Products': 'بەرهەمەکان',
    'Profile': 'پرۆفایل',
    'Profile settings': 'ڕێکخستنەکانی پرۆفایل',
    'Profile updated.': 'پرۆفایل نوێکرایەوە.',
    'Project Task Id': 'ناسنامەی ئەرکی پرۆژە',
    'Project tasks': 'ئەرکەکانی پرۆژە',
    'Purchase Cost': 'تێچووی کڕین',
    'Purchase Date': 'بەرواری کڕین',
    'Purchase Price': 'نرخی کڕین',
    'Purchase orders': 'فەرمانەکانی کڕین',
    'Purchase price': 'نرخی کڕین',
    'Quality Score': 'نمرەی جۆری',
    'Quality control': 'کۆنترۆلی جۆری',
    'Quantity': 'بڕ',
    'Quantity change': 'گۆڕانی بڕ',
    'Quotation date': 'بەرواری پێشنیار',
    'Quotations': 'پێشنیارەکان',
    'Rate': 'ڕێژە',
    'Rating': 'هەڵسەنگاندن',
    'Reason': 'هۆکار',
    'Record ID': 'ناسنامەی تۆمار',
    'Record a new business expense': 'تۆمارکردنی خرجییەکی بازرگانی نوێ',
    'Record a new customer sale order': 'تۆمارکردنی فەرمانی فرۆشتنێکی نوێی کڕیار',
    'Record a new employee payroll': 'تۆمارکردنی مووچەیەکی نوێی کارمەند',
    'Record a new general ledger entry': 'تۆمارکردنی تۆمارێکی نوێی ژمێریاری گشتی',
    'Record a new payment transaction': 'تۆمارکردنی مامەڵەی پارەدانێکی نوێ',
    'Record a new sales invoice': 'تۆمارکردنی پسوڵەی فرۆشتنێکی نوێ',
    'Record a new sales quotation': 'تۆمارکردنی پێشنیارێکی فرۆشتنێکی نوێ',
    'Record a new supplier bill': 'تۆمارکردنی پسوڵەیەکی نوێی دابینکەر',
    'Record a new supplier purchase order': 'تۆمارکردنی فەرمانی کڕینێکی نوێی دابینکەر',
    'Record a stock quantity adjustment': 'تۆمارکردنی ڕێکخستنی بڕی کۆگا',
    'Record and track business expenses': 'تۆمارکردن و بەدواداچوون بە خرجییەکانی بازرگانی',
    'Record incoming and outgoing payments': 'تۆمارکردنی پارەدانە هاتوو و دەرچووەکان',
    'Recovery code': 'کۆدی گەڕانەوە',
    'Recovery codes': 'کۆدەکانی گەڕانەوە',
    'Recovery codes let you regain access if you lose your 2FA device. Store them in a secure password manager.': 'کۆدەکانی گەڕانەوە ڕێگەت پێدەدەن دووبارە بچیتە ژوورەوە ئەگەر ئامێری ٢FA لەدەست بدەیت. لە بەڕێوەبەری وشەی نهێنی پارێزراودا هەڵیان بگرە.',
    'Reference Number': 'ژمارەی ئاماژە',
    'Reference number': 'ژمارەی ئاماژە',
    'Regenerate codes': 'دووبارە دروستکردنی کۆدەکان',
    'Register passkey': 'تۆمارکردنی کلیلی چوونەژوورەوە',
    'Registering...': 'تۆمارکردن...',
    'Remember me': 'لەبیرم بمێنەرەوە',
    'Remove passkey': 'سڕینەوەی کلیلی چوونەژوورەوە',
    'Report type': 'جۆری ڕاپۆرت',
    'Repository': 'کۆگای کۆد',
    'Resend verification email': 'دووبارە ناردنی ئیمەیڵی پشتڕاستکردنەوە',
    'Reset password': 'نوێکردنەوەی وشەی نهێنی',
    'Restored': 'گەڕێندرایەوە',
    'Revenue': 'داهات',
    'Review Date': 'بەرواری پێداچوونەوە',
    'SKU': 'SKU',
    'SKU / Barcode': 'SKU / بارکۆد',
    'Salary': 'مووچە',
    'Sale Price': 'نرخی فرۆشتن',
    'Sale order': 'فەرمانی فرۆشتن',
    'Sale orders': 'فەرمانەکانی فرۆشتن',
    'Sale price': 'نرخی فرۆشتن',
    'Save changes': 'پاشەکەوتکردنی گۆڕانکارییەکان',
    'Search': 'گەڕان',
    'Search by employee number, name, email, department, or job title...': 'گەڕان بەپێی ژمارەی کارمەند، ناو، ئیمەیڵ، بەش یان ناونیشانی کار...',
    'Search by name, SKU, or description...': 'گەڕان بەپێی ناو، SKU یان وەسف...',
    'Search by name, code, address, or phone...': 'گەڕان بەپێی ناو، کۆد، ناونیشان یان تەلەفۆن...',
    'Search by name, code, or description...': 'گەڕان بەپێی ناو، کۆد یان وەسف...',
    'Search by name, company, email, phone, or tax number...': 'گەڕان بەپێی ناو، کۆمپانیا، ئیمەیڵ، تەلەفۆن یان ژمارەی باج...',
    'Search by reference, category, description, or contact...': 'گەڕان بەپێی ئاماژە، پۆل، وەسف یان پەیوەندی...',
    'Search by reference, contact, payment method, or notes...': 'گەڕان بەپێی ئاماژە، پەیوەندی، شێوازی پارەدان یان تێبینی...',
    'Search by reference, customer, or notes...': 'گەڕان بەپێی ئاماژە، کڕیار یان تێبینی...',
    'Search by reference, description, or notes...': 'گەڕان بەپێی ئاماژە، وەسف یان تێبینی...',
    'Search by reference, employee, or notes...': 'گەڕان بەپێی ئاماژە، کارمەند یان تێبینی...',
    'Search by reference, name, or notes...': 'گەڕان بەپێی ئاماژە، ناو یان تێبینی...',
    'Search by reference, product, warehouse, reason, or notes...': 'گەڕان بەپێی ئاماژە، بەرهەم، کۆگا، هۆکار یان تێبینی...',
    'Search by reference, supplier, or notes...': 'گەڕان بەپێی ئاماژە، دابینکەر یان تێبینی...',
    'Search by subject, description, or contact...': 'گەڕان بەپێی بابەت، وەسف یان پەیوەندی...',
    'Search by user, action, or model...': 'گەڕان بەپێی بەکارهێنەر، کردار یان مۆدێل...',
    'Security': 'ئاسایش',
    'Security settings': 'ڕێکخستنەکانی ئاسایش',
    'Select': 'هەڵبژاردن',
    'Select contact': 'پەیوەندی هەڵبژێرە',
    'Select customer': 'کڕیار هەڵبژێرە',
    'Select employee': 'کارمەند هەڵبژێرە',
    'Select product': 'بەرهەم هەڵبژێرە',
    'Select sale order': 'فەرمانی فرۆشتن هەڵبژێرە',
    'Select supplier': 'دابینکەر هەڵبژێرە',
    'Select warehouse': 'کۆگا هەڵبژێرە',
    'Settings': 'ڕێکخستنەکان',
    'Shift management': 'بەرێوەبردنی شیفت',
    'Shipping Method Id': 'ناسنامەی شێوازی گەیاندن',
    'Shipping methods': 'شێوازەکانی گەیاندن',
    'Show low stock only': 'تەنها کۆگای کەم پیشان بدە',
    'Sign in with a passkey': 'چوونەژوورەوە بە کلیلی چوونەژوورەوە',
    'Sku': 'SKU',
    'Slug': 'سلەگ',
    'Source': 'سەرچاوە',
    'Spent Amount': 'بڕی خەرجکراو',
    'Start Date': 'بەرواری دەستپێک',
    'Start Free Trial': 'دەستپێکردنی تاقیکردنەوەی بەخۆڕایی',
    'Start Time': 'کاتی دەستپێک',
    'Statement Date': 'بەرواری ڕاپۆرت',
    'Stock': 'کۆگا',
    'Stock Quantity': 'بڕی کۆگا',
    'Stock quantity': 'بڕی کۆگا',
    'Stock transfers': 'گواستنەوەکانی کۆگا',
    'Subject': 'بابەت',
    'Subscriptions': 'بەشداربوونەکان',
    'Supplier evaluations': 'هەڵسەنگاندنەکانی دابینکەر',
    'System': 'سیستەم',
    'Tax amount': 'بڕی باج',
    'Tax number': 'ژمارەی باج',
    'Tax rates': 'ڕێژەکانی باج',
    'Tickets': 'تیکتەکان',
    'Time logs': 'تۆمارەکانی کات',
    'Title': 'ناونیشان',
    'To Warehouse Id': 'ناسنامەی کۆگای مەبەست',
    'To finish enabling two-factor authentication, scan the QR code or enter the setup key in your authenticator app.': 'بۆ تەواوکردنی چالاککردنی پشتڕاستکردنەوەی دوو هەنگاوە، QR کۆد سکان بکە یان کلیلی ڕێکخستن لە ئەپلیکەیشنی پشتڕاستکەرەوە بنووسە.',
    'Total amount': 'کۆی بڕ',
    'Total credit': 'کۆی قەرزدار',
    'Total debit': 'کۆی قەرزخواز',
    'Total expenses': 'کۆی خرجییەکان',
    'Total revenue': 'کۆی داهات',
    'Track customer calls, emails, meetings, and notes': 'بەدواداچوون بە پەیوەندی، ئیمەیڵ، کۆبوونەوە و تێبینییەکانی کڕیار',
    'Track stock corrections and quantity changes': 'بەدواداچوون بە ڕاستکردنەوەی کۆگا و گۆڕانی بڕ',
    'Track supplier orders and incoming inventory': 'بەدواداچوون بە داواکارییەکانی دابینکەر و کۆگای هاتوو',
    'Transfer Date': 'بەرواری گواستنەوە',
    'Trip Date': 'بەرواری گەشت',
    'Two-factor authentication': 'پشتڕاستکردنەوەی دوو هەنگاوە',
    'Two-factor authentication enabled': 'پشتڕاستکردنەوەی دوو هەنگاوە چالاککرا',
    'Two-factor authentication is now enabled. Scan the QR code or enter the setup key in your authenticator app.': 'پشتڕاستکردنەوەی دوو هەنگاوە ئێستا چالاکە. QR کۆد سکان بکە یان کلیلی ڕێکخستن لە ئەپلیکەیشنی پشتڕاستکەرەوە بنووسە.',
    'Unit': 'یەکە',
    'Update password': 'نوێکردنەوەی وشەی نهێنی',
    'Update the appearance settings for your account': 'نوێکردنەوەی ڕێکخستنەکانی ڕواڵەت بۆ هەژمارەکەت',
    'Update your name and email address': 'نوێکردنەوەی ناو و ناونیشانی ئیمەیڵەکەت',
    'Updated': 'نوێکراوە',
    'Usage Limit': 'سنووری بەکارهێنان',
    'User': 'بەکارهێنەر',
    'Valid From': 'کارا لە',
    'Valid Until': 'کارا تا',
    'Value': 'نرخ',
    'Variants': 'جۆرەکان',
    'Vehicle Plate': 'ژمارەی ئۆتۆمبیل',
    'Vehicle maintenance': 'چاککردنەوەی ئۆتۆمبیل',
    'Verify authentication code': 'پشتڕاستکردنەوەی کۆدی پشتڕاستکردنەوە',
    'View recovery codes': 'بینینی کۆدەکانی گەڕانەوە',
    'View system activity and change history': 'بینینی چالاکی سیستەم و مێژووی گۆڕانکاری',
    'Warehouse Id': 'ناسنامەی کۆگا',
    'Warehouses': 'کۆگاکان',
    'When you enable two-factor authentication, you will be prompted for a secure pin during login. This pin can be retrieved from a TOTP-supported application on your phone.': 'کاتێک پشتڕاستکردنەوەی دوو هەنگاوە چالاک دەکەیت، لە کاتی چوونەژوورەوە داوات لێدەکرێت PINێکی پارێزراو بنووسیت. ئەم PINە لە ئەپلیکەیشنێکی پشتگیریکراوی TOTP لە مۆبایلەکەتدا دەستدەکەوێت.',
    'Width': 'پانی',
    'Yes': 'بەڵێ',
    'You will be prompted for a secure, random pin during login, which you can retrieve from the TOTP-supported application on your phone.': 'لە کاتی چوونەژوورەوە داوات لێدەکرێت PINێکی پارێزراو و هەڕەمەکی بنووسیت، کە لە ئەپلیکەیشنێکی پشتگیریکراوی TOTP لە مۆبایلەکەتدا دەستدەکەوێت.',
    'Your email address is unverified.': 'ناونیشانی ئیمەیڵەکەت پشتڕاست نەکراوە.',
    'e.g., MacBook Pro, iPhone': 'وەک MacBook Pro، iPhone',
    'log in': 'چوونەژوورەوە',
    'login using a recovery code': 'چوونەژوورەوە بە کۆدی گەڕانەوە',
    'login using an authentication code': 'چوونەژوورەوە بە کۆدی پشتڕاستکردنەوە',
    'or you can': 'یان دەتوانیت',
    'or, enter the code manually': 'یان، کۆدەکە بە دەست بنووسە',
}
